# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 014de0796f9102f21409657923d3ab654f50d6645d92ccab3ad5481aacbd85493d14bbe9db102dd4b61bd2b432009eb8e4fbd32ad523822fd86d58151d4e3cea

test:
  secret_key_base: 78c2da45617604f227b89578de4ac8b5b8cda222c29f6151b7932158362cc3fe8cb2ea4a05830cae4a49a02cfff4cc78b787f6ebaf522096af4ce6dd2a9774c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
